"""sync database schema

Revision ID: 442a2da977ec
Revises: 
Create Date: 2026-09-10 07:44:00.252184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442a2da977ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_analyses',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=False),
    sa.Column('request_example', sa.Text(), nullable=False),
    sa.Column('response_example', sa.Text(), nullable=False),
    sa.Column('test_cases', sa.Text(), nullable=False),
    sa.Column('security_recommendations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['api_endpoints.endpoint_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_api_analyses_analysis_id'), 'api_analyses', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_api_analyses_endpoint_id'), 'api_analyses', ['endpoint_id'], unique=False)
    op.add_column('projects', sa.Column('base_url', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'base_url')
    op.drop_index(op.f('ix_api_analyses_endpoint_id'), table_name='api_analyses')
    op.drop_index(op.f('ix_api_analyses_analysis_id'), table_name='api_analyses')
    op.drop_table('api_analyses')
    # ### end Alembic commands ###
